# Generated by Django 5.0.6 on 2024-05-22 06:07

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('admin', 'Admin'), ('mentor', 'Mentor')], max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('is_paid', models.BooleanField(default=True)),
                ('published_title', models.CharField(max_length=255)),
                ('visible_instructors', models.ManyToManyField(to='que_forum.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('created', models.DateTimeField()),
                ('num_replies', models.IntegerField()),
                ('num_follows', models.IntegerField()),
                ('num_reply_upvotes', models.IntegerField()),
                ('modified', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('is_read', models.BooleanField(default=False)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_instructor', models.BooleanField(default=False)),
                ('num_upvotes', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='que_forum.course')),
            ],
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField()),
                ('last_activity', models.DateTimeField()),
                ('body', models.TextField()),
                ('is_top_answer', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='que_forum.profile')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='que_forum.question')),
            ],
        ),
    ]
