# Generated by Django 5.0.6 on 2024-05-29 10:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que_forum', '0002_course_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customuser',
            options={},
        ),
        migrations.AlterModelTable(
            name='course',
            table='que_forum_courses',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='que_forum_users',
        ),
    ]
