# Generated by Django 5.0.6 on 2024-05-23 09:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que_forum', '0002_alter_user_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
