# Generated by Django 5.0.6 on 2024-05-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que_forum', '0003_delete_user'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='answer',
            table='answers',
        ),
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='question',
            table='questions',
        ),
    ]
