# Generated by Django 5.0.6 on 2024-05-29 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que_forum', '0003_alter_customuser_options_alter_course_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='course',
            table='courses',
        ),
        migrations.AlterModelTable(
            name='customuser',
            table='users',
        ),
    ]
