# Generated by Django 5.0.6 on 2024-05-30 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('que_forum', '0004_alter_course_table_alter_customuser_table'),
    ]

    operations = [
        migrations.CreateModel(
            name='MentorCourseAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentor_course_assignments', to='que_forum.course')),
                ('mentor', models.ForeignKey(limit_choices_to={'role': 'mentor'}, on_delete=django.db.models.deletion.CASCADE, related_name='mentor_course_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_course_assignments',
            },
        ),
    ]
