# Generated by Django 5.0.6 on 2024-05-30 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('que_forum', '0005_mentorcourseassignment'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='customusers',
        ),
    ]
